// js/AppState.js
import * as THREE from 'three';

export const AppState = {
    apiPort: null,
    apiBaseUrl: '',
    activeTool: 'select',
    isZoneEditMode: false,
    isReviewMode: false,
    isLoadingModel: false,
    selectedStickerChar: null,
    definedZones: [],
    placedStickers: [],
    decalMeshes: [],
    zoneManager: null,
    uiManager: null,
    performance: { fps: 0, triangles: 0, drawCalls: 0 },
    actionHistory: [],
    redoStack: [],
    animation: { mixer: null, actions: [], clock: new THREE.Clock() },
    scene: null,
    camera: null,
    renderer: null,
    orbitControls: null,
    transformControls: null,
    loadedModel: null,
    originalMaterials: new Map(),
    bronzeMaterial: null,
    paintGroup: null,
    zoneMarkersGroup: null,
    modelScale: 1,
    stickerSize: 0.15,
    textureCache: new Map(),
    materialCache: new Map(),
    emojiStickerTextureCache: new Map(),
};